### ISSUE TITLE
Non-shop menu issue

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront-hamburger-menu#2]
On my blog, this happens when using the extension:

![](http://cld.wthms.co/1gWMc/1i0k55hN+)

I'm not using WooCommerce, so the cart icon in the header is missing.
Also, the background for main items is not showing and the icon is misplaced on the top right.

**Comment by tiagonoronha** [comment]
@SiR-DanieL mind testing with the latest version of the plugin? Thanks

**Comment by SiR-DanieL** [comment]
This is how it looks:

![](http://cld.wthms.co/1f3mo/46d5fubJ+)

Notice the Hamburger icon which is off, on the top right. It should be aligned with the site name.

Also, personally I don't like that ti's transparent. I'd prefer it like this:

![](http://cld.wthms.co/1iUNR/1NQMPHQG+)

Using the same color of the header.

**Comment by tiagonoronha** [comment]
@SiR-DanieL good catch!

Should be good now. :)

**Comment by SiR-DanieL** [comment]
It works now! But the responsive in Storefront 2.0 is broken for the header and this extension breaks it even more.

See: https://github.com/woothemes/storefront/issues/378
