### ISSUE TITLE
BUGS in the HAMBURGER! (....yummy!) 

### ISSUE THREAD

**Issue by BurlesonBrad** [woothemes/storefront-hamburger-menu#4]
@tiagonoronha :  I've checked several different phone types w/ several different sites & then checked and verified the display bugs can be replicated using Chrome's Inspect Element. _(that way we can all be seeing the same thing)_ :+1: 

![hamburger-open-iphone6](https://cloud.githubusercontent.com/assets/6208757/15269897/f235518a-19d2-11e6-8a9f-bd9d8925b8d9.png)

![hamburger-open-galaxys](https://cloud.githubusercontent.com/assets/6208757/15269902/279b7dea-19d3-11e6-91f2-205d61974c72.png)

![hamburger-open-galaxy5](https://cloud.githubusercontent.com/assets/6208757/15269905/415c0060-19d3-11e6-9806-4886c2da32cd.png)

When closed, there's an additional line on the top right of the menu. Then, when open, there's additional lines that don't seem to form in anything _(like an 'X')_ as anticipated:
![screenshot-1 9](https://cloud.githubusercontent.com/assets/6208757/15269967/0b9878f8-19d5-11e6-8f62-7e28db9af54b.png)

**Comment by apsolut** [comment]
Confirmation: 
![storefront-hamburger-bug](https://cloud.githubusercontent.com/assets/1828768/15297075/a3ad2bce-1b98-11e6-92be-cfa87bf69272.gif)

**Comment by tiagonoronha** [comment]
@BurlesonBrad @apsolut thanks for this, will work on a fix tomorrow. 👍
