### ISSUE TITLE
Does not work in Child Themes 

### ISSUE THREAD

**Issue by Mariacakovacs** [woothemes/storefront-hamburger-menu#5]
I just download the hamburger menu to set up a test shop, i am using a child theme called "stile"  but does not work

**Comment by tiagonoronha** [comment]
@Mariacakovacs That doesn't seem to be one of our child themes?

https://www.woothemes.com/product-category/themes/storefront-child-theme-themes/

**Comment by BurlesonBrad** [comment]
@Mariacakovacs the **Storefront Hamburger Menu** is only meant to be consumed by the **Storefront Theme.** Consuming, eating, using, or ingesting the Hamburger menu on any other theme is **not recommended** by the WooThemes Health Department!
