### ISSUE TITLE
Carnivore vs. Vegetarian in Galleria

### ISSUE THREAD

**Issue by BurlesonBrad** [woothemes/storefront-hamburger-menu#6]
## Carnivore: 
_(With Hamburger)_:
----------------
![screenshot_2016-07-31-11-33-44](https://cloud.githubusercontent.com/assets/6208757/17279090/2a01f996-5732-11e6-8910-6ffc5cd9021e.png)
-----------------
![screenshot_2016-07-31-11-35-42](https://cloud.githubusercontent.com/assets/6208757/17279093/4668d438-5732-11e6-9b8f-b8d47ce4f49d.png)

-----------------------
## Vegetarian: 
(With**_OUT_** Hamburger):
![screenshot_2016-07-31-15-22-07](https://cloud.githubusercontent.com/assets/6208757/17279150/3c9833f8-5733-11e6-9246-e6a1f0868bed.png)

annoying git tag going out to @mikejolley

**Comment by tiagonoronha** [comment]
@BurlesonBrad 

Hey Brad, this is something that we need to adjust in Galleria.

Keep an eye for an update!
